"""Writes Bed Management Solutions turns bm-so-02 to bm-so-12 (transcript turns 19 to 31) and turns.json.
bm-so-01 (transcript 18) is written by make_bm_so_01.py; its Sample A is the turn.
Transcript turns 24 and 25 were superseded in the record by 27 and 28, so they are not drawn.
Every spec records the user's message, the chat (text, bullets, note, @points, three prompts) and the canvas,
with the three buttons on every turn. Draw with ../../solutions-html-generator/bm_solutions_html.py build."""
import json, os
HERE = os.path.dirname(os.path.abspath(__file__))

def S(key, when, title, text, lines=(), entry=None, hint=None, ask=None):
    s = {'key': key, 'when': when, 'title': title, 'text': text}
    if lines: s['lines'] = [dict(zip(('label', 'value', 'state'), l)) for l in lines]
    if entry: s['entry'] = entry
    if hint: s['entry_hint'] = hint
    if ask: s['ask'] = {'label': ask[0], 'say': ask[1]}
    return s

def acts(step, say_go, add='Add something about your hospital', add_say='Here is something to add about our hospital: ', jump='How the automations are built and run'):
    return {'go': {'detail': step, 'say': say_go}, 'add': {'detail': add, 'say': add_say}, 'jump': {'tab': 'Automations', 'detail': jump, 'say': 'Take me to Automations'}}

def turn(n, tno, label, user, context, chat, blocks, actions, note):
    return {'turn': {'id': 'bm-so-%02d' % n, 'tab': 'Solutions', 'type': 'part', 'register': 'advisory', 'tool': 'Bed Management', 'user_message': user,
                     'context': context, 'transcript': {'label': 'Transcript turn %d · %s' % (tno, label)}},
            'chat': chat, 'canvas': {'blocks': blocks, 'actions': actions}, '_note': note,
            'review': {'status': 'approved', 'date': '2026-10-01', 'note': 'Approved 1 Oct with the Bed Management Solutions turns.'}}

def pts(*labels): return [{'n': i + 1, 'label': x, 'canvas': True} for i, x in enumerate(labels)]
def plate(n, name): return {'part': n, 'of': 5, 'name': name, 'stage': 'Shaped'}
STEPS6 = ['Admission advice recorded', 'First mapping of tomorrow', 'Teams told', 'Evening round confirms', 'Tomorrow’s plan frozen', 'Call-in times sent']

T = []

# ---------------------------------------------------------------------------------------------- 02 · transcript 19
T.append(turn(2, 19, '“How would all of these be achieved?”', 'so how would all of these be achieved? there seems to be multiple things to be done.',
    'How the automation part is achieved, at the level of the answer: what the hospital provides, the one build, what comes out, the one prerequisite and the one blocker.',
    {'text': ['The chain showed the order. It did not show how little of it is separate work.'],
     'bullets': ['Six steps, but not six projects. Almost all of it comes out of one engine reading data you already hold.',
                 'The mapping, the alerts, the freeze and the call-in times are outputs of that one engine. They are not builds of their own.',
                 'What you provide is short. Read access to systems you already run, two small changes in habit, and one report in billing.'],
     'pointer': 'The drawing splits it into what you provide, what we build and what comes out. Pick anything you provide to see what it feeds.',
     'invite': 'Tell me which of these you want to go into, or pick another of the five parts.',
     'note': 'Six steps, one engine, one connection to your systems.',
     'points': pts('Read access', 'The two habits', 'The billing report', 'Discharge comes first', 'The IT connection'),
     'prompts': ['Will you be doing all of this for me?', 'What if we don’t have such systems?', 'Why must discharge come first?']},
    [{'type': 'heading', 'eyebrow': 'Part 1 · Automations', 'title': 'Six steps, one engine', 'plate': plate(1, 'Automations'),
      'deck': 'What you provide, what we build and what comes out. Most of it is one build, reading data you already hold.'},
     {'type': 'hub', 'in_label': 'What you provide', 'out_label': 'What comes out',
      'inputs': [{'kind': 'Read access', 'title': 'Admissions and discharges', 'line': 'Who came in, who left, and when', 'feeds': [2, 5, 6], 'point': 1},
                 {'kind': 'Read access', 'title': 'OPD and inpatient records', 'line': 'The advice to admit, the procedure, the stay so far', 'feeds': [1, 2], 'point': 1},
                 {'kind': 'A small habit', 'title': 'Doctors check a date on the round', 'line': 'Confirm or correct the predicted date', 'feeds': [4, 5], 'point': 2},
                 {'kind': 'A small habit', 'title': 'One fixed round at 5 PM', 'line': 'Medical Supervisory confirm tomorrow’s discharges', 'feeds': [4, 5], 'point': 2},
                 {'kind': 'One report', 'title': 'Bill close and bill open, against the bed', 'line': 'Turns dead bed time into a number you can track', 'feeds': [], 'point': 3}],
      'engine': {'label': 'What we build', 'title': 'One mapping engine', 'line': 'Reads what you already hold. Gives every step its answer.'},
      'outputs': STEPS6,
      'sheets': [S('adm', 'Read access', 'Admissions and discharges', 'The engine reads who came in, who left and when. It writes nothing back. It needs no new work from the desk.',
                   [('Who gives it', 'Your IT team, once'), ('Feeds', 'The mapping, the freeze and the call-in times')], 'Which system holds admissions at your hospital today?', 'For example, the hospital system or a register'),
                 S('rec', 'Read access', 'OPD and inpatient records', 'The advice to admit, the procedure and the stay so far. This is what lets the engine see which beds are likely to free up.',
                   [('Who gives it', 'Your IT team, once'), ('Feeds', 'The advice recorded and the 2 PM mapping')], 'Are your OPD notes on a system or on paper?'),
                 S('date', 'A small habit', 'Doctors check a date on the round', 'The system puts a predicted discharge date in front of the doctor. The doctor confirms it or corrects it. Nobody is asked to produce a date.',
                   [('Who', 'The treating doctor, on the round they already do'), ('Feeds', 'The 5 PM round and the freeze')], 'How do your doctors pass on discharge plans today?'),
                 S('five', 'A small habit', 'One fixed round at 5 PM', 'Medical Supervisory look only at beds expected to free up tomorrow. They confirm or correct them by 5 PM, so the plan can freeze at 6 PM.',
                   [('Who', 'Medical Supervisory'), ('Feeds', 'The 5 PM round and the freeze')], 'Who does an evening round at your hospital today?'),
                 S('bill', 'One report', 'Bill close and open, against the bed', 'Both times already sit in your billing system. Nobody has put them side by side against the same bed. That is one report, not new data.',
                   [('Who', 'Billing, with IT'), ('Gives', 'Dead bed time, every week, bed by bed', 'start')], 'Which billing system do you run?')]},
     {'type': 'pair', 'items': [
        {'label': 'What must come first', 'value': 'Discharge, automated', 'state': 'target', 'point': 4,
         'sub': 'The bed plan runs on discharge times. So Bed Management cannot be bought on its own.', 'ask': {'label': 'Ask about this', 'say': 'Why must discharge be automated first?'}},
        {'label': 'One blocker', 'value': 'The IT connection', 'state': 'outcome', 'point': 5,
         'sub': 'Without read access to your systems, nothing runs. Everything after that is ours to build.', 'ask': {'label': 'Ask about this', 'say': 'What exactly would our IT team have to do?'}}]}],
    acts('Next: what we bring, and what must be there', 'So, will you be doing all of this for me?'),
    'The hub: five things the hospital provides, wired into one engine, six steps out. Then the prerequisite and the blocker as a pair.'))

# ---------------------------------------------------------------------------------------------- 03 · transcript 20
T.append(turn(3, 20, '“Will you be doing all of this for me? What if I don’t have such systems?”', 'so, you will be doing all of this for me? what if i dont have such systems already?',
    'What Tojo brings against what must already exist, and the honest threshold: a hospital mostly on paper is a different project.',
    {'text': ['Most of it is ours. A small part is not, and it is better said now.'],
     'bullets': ['We bring the recording. Voice notes on rounds, with our own recorder. Prescriptions read at OPD. Each admission step timed as it happens.',
                 'Two things have to be there already. Read access to what holds admissions, discharges, tests and charges. And one report on your billing system.',
                 'If almost nothing is digital, this is a different project, not a slower one. The recording layer gets much bigger.'],
     'pointer': 'Pick a box to open it. Then switch the building to a hospital still on paper.',
     'invite': 'Next are the other four parts. Shall I show you what else we would be doing?',
     'note': 'We bring the recording. You bring the access.',
     'points': pts('Voice notes on rounds', 'Prescriptions read at OPD', 'Admission steps timed', 'Read access', 'The billing report'),
     'prompts': ['Other than these, what else would we be doing?', 'Most of our records are on paper', 'Who in IT would we need?']},
    [{'type': 'heading', 'eyebrow': 'Part 1 · Automations', 'title': 'What we bring, what must be there', 'plate': plate(1, 'Automations'),
      'deck': 'Above the line is ours. Below it is what we stand on, and it has to exist before we start.'},
     {'type': 'foundation', 'bring_label': 'We bring this', 'there_label': 'This has to be there', 'ground': 'The ground line: what we stand on',
      'bring': [{'title': 'Voice notes on rounds', 'line': 'Our own recorder and our own transcription', 'point': 1},
                {'title': 'Prescriptions read at OPD', 'line': 'Read as written, not a form for somebody to fill in', 'point': 2},
                {'title': 'Admission steps timed', 'line': 'Each step stamped as the new flow runs', 'point': 3}],
      'there': [{'title': 'Read access', 'line': 'To whatever holds admissions, discharges, tests and charges today', 'point': 4},
                {'title': 'One billing report', 'line': 'Bill close and bill open, joined against the bed', 'point': 5}],
      'switch': {'label': 'How much is digital', 'yes': 'Most of it is digital', 'no': 'Almost nothing is',
                 'extra': 'A much bigger recording layer. Most of the record has to be recorded first.',
                 'read_yes': 'With these two in place, the rest is ours to build.', 'read_no': 'A different project, not a slower one. Better said now than found out later.'},
      'sheets': [S('voice', 'We bring this', 'Voice notes on rounds', 'The doctor speaks on the round they already do. Our recorder and our transcription turn it into a note. Nobody types it again.',
                   [('Who it helps', 'Doctors, and the discharge plan'), ('Needs from you', 'Nothing but the round')], 'Do your doctors record notes on rounds today?'),
                 S('opd', 'We bring this', 'Prescriptions read at OPD', 'The advice to admit is read from the prescription as the doctor writes it. It is not a form for somebody to fill in.',
                   [('Who it helps', 'The admissions desk'), ('Needs from you', 'The prescription, as it is written now')], 'How are OPD prescriptions written now?', 'For example, on paper or on a system'),
                 S('steps', 'We bring this', 'Admission steps timed', 'Each of the five admission steps is stamped as it happens. That is what shows coordination time apart from paperwork.',
                   [('Who it helps', 'The Bed Manager, and you'), ('Needs from you', 'Nothing new')], 'Do you time any admission steps today?'),
                 S('access', 'Has to be there', 'Read access', 'We read whatever holds admissions, discharges, tests and charges today. We write nothing back.',
                   [('Who gives it', 'Your IT team'), ('If it is missing', 'Nothing runs', 'outcome')], 'Which systems hold this today?'),
                 S('report', 'Has to be there', 'One billing report', 'Your billing system holds the time each bill closes and opens. One report joins them against the same bed.',
                   [('Who', 'Billing, with IT'), ('It is', 'A report, not new data')], 'Who builds reports on your billing system?')]},
     {'type': 'effect', 'label': 'If almost nothing is digital', 'value': 'A different project', 'state': 'outcome',
      'sub': 'Not a slower one. The recording layer grows, and the timeline changes with it.'}],
    acts('Next: what else we would be doing', 'Other than these automations, what else would we be doing?'),
    'The foundation: what Tojo brings above the ground line, the two things that must exist below it, and a switch to a hospital still on paper.'))

# ---------------------------------------------------------------------------------------------- 04 · transcript 21
DOORQ = [('Automations', 'What we build, and what it needs from you'),
         ('Process changes', 'What changes in how the day is run, and what that change costs you'),
         ('People and buy-in', 'Whose help this needs, and who signs it off'),
         ('Teams and roles', 'Whether you need to hire, who, and how many, on your own numbers'),
         ('Measures', 'How you would know, week to week, whether any of it is working')]
T.append(turn(4, 21, '“Other than these automations, what else would you be doing?”', 'understood. other than these automations, what else would you/we be doing?',
    'A progress view, not a replay: one part covered, four to go, each door carrying the question its part answers. No arrows: the parts are independent.',
    {'text': ['One part covered, four to go. Each door carries the question its part answers.', 'You can take them in any order.'],
     'pointer': 'Pick a door to see what that part covers.',
     'invite': 'Which part would you like next?',
     'note': 'Four questions left. Take them in any order.',
     'points': pts('Process changes', 'People and buy-in', 'Teams and roles', 'Measures'),
     'prompts': ['Let us start with the process changes', 'Who needs to agree to all this?', 'Do we need to hire anyone?']},
    [{'type': 'heading', 'eyebrow': 'The five parts', 'title': 'One part covered, four to go', 'deck': 'Each closed door carries the question its part answers. The covered one stands open.'},
     {'type': 'doors', 'default': 2, 'corridor': 'One corridor. The doors open in any order.',
      'doors': [dict({'n': i + 1, 'title': t, 'question': q}, **({'state': 'covered', 'tag': 'Covered'} if i == 0 else {'state': 'closed', 'point': i})) for i, (t, q) in enumerate(DOORQ)],
      'sheets': [S('p1', 'Part 1 · covered', 'Automations', 'Covered in the last three answers. Six steps, one engine, and read access from your IT team.',
                   [('Where it stands', 'Shaped', 'start')], ask=('Go back to part 1', 'Take me back to part 1, the automations')),
                 S('p2', 'Part 2', 'Process changes', 'What changes in how the day is run. The biggest change costs nothing but the order work is done in.',
                   [('It answers', DOORQ[1][1])], 'What would you most like to change in your day?', ask=('Open part 2', 'Let us start with the process changes')),
                 S('p3', 'Part 3', 'People and buy-in', 'Whose help this needs, where the resistance sits, and who signs the new flows off.',
                   [('It answers', DOORQ[2][1])], 'Who would push back hardest at your hospital?', ask=('Open part 3', 'Take me through part 3, the people and their buy-in')),
                 S('p4', 'Part 4', 'Teams and roles', 'Whether you need to hire, who, and how many. Sized on your own numbers, not a rule of thumb.',
                   [('It answers', DOORQ[3][1])], 'How many people run your admissions desk today?', ask=('Open part 4', 'Take me through part 4, the teams and roles')),
                 S('p5', 'Part 5', 'Measures', 'The few numbers you would check every week, and which of them nobody measures today.',
                   [('It answers', DOORQ[4][1])], 'Which numbers do you look at each week now?', ask=('Open part 5', 'Take me through part 5, the measures'))]}],
    acts('Next: part 2, the process changes', 'Let us start with the process changes'),
    'The corridor of doors from the Solutions landing page: part 1 ajar and covered, four closed doors each carrying its question.'))

# ---------------------------------------------------------------------------------------------- 05 · transcript 22
T.append(turn(5, 22, 'Part 2: Process changes', 'process changes',
    'The approved shape: one big change, four small ones, two owners, then the ask. The decoupling is the hospital’s own answer from Diagnosis.',
    {'text': ['Process changes next. One big change, four small ones, and two owners.'],
     'bullets': ['The big one: admissions and discharges stop running one after the other. Two teams, or the two windows run together.',
                 'Four smaller changes hold it up. Each one costs a change in order, not money.',
                 'The bed plan is only as good as the discharge times it is built on. So both sides need an owner, and neither reports to the other.'],
     'pointer': 'Switch between the day now and the day as it would run. Then pick a change or an owner.',
     'question': {'text': 'Do you have someone on this job full time?', 'options': ['Yes, someone does it full time', 'We would look at creating the role', 'Tell me the reasoning in more detail']},
     'invite': 'After this comes part 3, the people and their buy-in.',
     'note': 'The bed plan is only as good as the discharge times it is built on.',
     'points': pts('The day now', 'The day as it would run', 'The four smaller changes', 'The Bed Manager', 'The Discharge Manager'),
     'prompts': ['A hospital is too dynamic. Will such rules work?', 'Tell me more about why a Discharge Manager is needed', 'Next, part 3, the people']},
    [{'type': 'heading', 'eyebrow': 'Part 2 · Process changes', 'title': 'Run the two jobs together', 'plate': plate(2, 'Process changes'),
      'deck': 'Today one team discharges, then admits. The change is to run both at once, against beds that will be free.'},
     {'type': 'day-switch', 'from': '8:00', 'to': '20:00',
      'lanes': [{'name': 'Discharges', 'now': [{'from': '9:00', 'to': '13:00', 'label': 'Discharges first'}], 'with': [{'from': '9:00', 'to': '13:00', 'label': 'Discharges, as before'}]},
                {'name': 'Admissions', 'now': [{'from': '13:00', 'to': '17:00', 'label': 'Admissions after'}], 'with': [{'from': '9:30', 'to': '12:30', 'label': 'Admissions alongside', 'state': 'start'}]},
                {'name': 'Patient in a bed', 'now': [{'from': '16:30', 'to': '20:00', 'label': '4:30 to 8 PM', 'state': 'outcome'}],
                 'with': [{'from': '11:00', 'to': '12:30', 'label': 'By about noon', 'state': 'start'}]}],
      'switch': {'now': 'The day now', 'with': 'The day it would be',
                 'cap_now': 'One team. Discharges first, then admissions. Patients reach a bed between 4:30 and 8 PM.',
                 'cap_with': 'Both jobs run together, against beds that will be free. The goal is a bed by about noon.'},
      'caption': 'Your own times: patients arrive at about 1 PM and reach a bed between 4:30 and 8 PM. The noon time is a goal.'},
     {'type': 'notes', 'label': 'Four smaller changes',
      'items': [{'tag': 'No cost', 'title': 'Give beds forward', 'text': 'Give a bed against when it will be free, not once it is ready.', 'point': 3},
                {'title': 'A date a day ahead', 'text': 'The system shows the doctor a predicted date to check.', 'point': 3},
                {'title': 'OPD advice first', 'text': 'Every planned admission starts from the advice in OPD.', 'point': 3},
                {'title': 'One billing report', 'text': 'Bill close and bill open, read against the same bed.', 'point': 3}],
      'sheets': [S('fwd', 'Change 1', 'Give beds forward', 'Today a bed is given only once it is confirmed ready. Give it against when it will be free instead. The same people and beds then make a different day.',
                   [('Costs', 'Nothing but the order work is done in', 'start')], 'When does your desk give a bed today?'),
                 S('date', 'Change 2', 'A date a day ahead', 'The doctor is shown a predicted discharge date to confirm or correct. That is a check, not a guess. It makes the evening plan possible.',
                   [('Today', 'An informal mention on rounds')], 'How early do your doctors say who goes home?'),
                 S('opd', 'Change 3', 'OPD advice first', 'Every planned admission starts from the doctor’s advice in OPD, with the date and the procedure. The mapping works from that.',
                   [('Needs', 'The prescription, read as it is written')], 'Where does a planned admission start at your hospital?'),
                 S('bill', 'Change 4', 'One billing report', 'Both times already exist in billing. What does not exist is the join against the bed. That turns dead bed time into a number you can track.',
                   [('It is', 'A report, not new data')], 'Who could run this report?')]},
     {'type': 'owners', 'label': 'Two owners', 'link': 'Peers. Neither reports to the other.',
      'line': 'Give only one side an owner, and the side without one sets the pace.',
      'owners': [{'tag': 'New role', 'title': 'Bed Manager', 'line': 'Holds tomorrow’s plan. Decides which patient goes to which bed, and when to call each one.', 'point': 4},
                 {'tag': 'New role', 'title': 'Discharge Manager', 'line': 'Owns every discharge, from the doctor’s word to the empty bed.', 'point': 5}],
      'sheets': [S('bm', 'New role', 'Bed Manager', 'Holds the plan, decides which patient goes to which bed, and sorts out late beds. On a busy day the patient at the desk wins, so a desk role cannot hold tomorrow’s plan.',
                   [('Reports to', 'The Head of Operations')], 'Does anyone hold the bed plan today?'),
                 S('dm', 'New role', 'Discharge Manager', 'Owns every discharge as one chain. Without this owner the Bed Manager spends the day chasing other people’s work.',
                   [('Reports to', 'The Head of Operations'), ('Needed above', '80% of beds full or 40 patients a day', 'target')], 'Who chases a slow discharge today?')]},
     {'type': 'effect', 'label': 'Discharge Manager', 'value': 'Both lines crossed', 'state': 'target',
      'sub': 'Needed above 80% of beds full or 40 patients a day. You are at 89% and about 41. The 41 is worked out from your figures.'}],
    acts('Next: will fixed times hold on a busy day?', 'A hospital is too dynamic. Will such hard rules actually work?'),
    'The day now against the day as it would run, on your clock. Then the four smaller changes and the two owners joined as peers.'))

# ---------------------------------------------------------------------------------------------- 06 · transcript 23
T.append(turn(6, 23, '“A hospital is too dynamic. Will such hard rules work?”', 'a hospital is too dynamic. will such hard rules actually be possible to implement? there will be a lot of resistance',
    'Two objections, two treatments. Resistance is conceded and parked for part 3. Too dynamic is tested against the hospital’s own figures.',
    {'text': ['Resistance is real, and it is most of part 3. But too dynamic is worth testing first, because your numbers point the other way.'],
     'bullets': ['89% full, a 6.5 day stay, about 41 admissions a day. The total is steady, even though no single bed is.',
                 'What is unknown is which bed frees when. What is known is how many will free, and roughly when. The mapping only uses that.',
                 'What is fixed is when a decision is made, not what is decided. When something moves, the plan re-runs and only the affected times change.'],
     'pointer': 'Follow the routes through the maze. Then try a change and watch the plan re-run.',
     'invite': 'Resistance deserves more than a line. Shall I take you into part 3?',
     'note': 'Fix when decisions are made, not what is decided.',
     'points': pts('Fix what gets decided', 'No fixed times', 'Fix when decisions are made', 'Something changes', 'The change is recorded'),
     'prompts': ['Yes, take me into part 3', 'Tell me more about why a Discharge Manager is needed', 'What if a doctor will not give a date?']},
    [{'type': 'heading', 'eyebrow': 'Part 2 · Process changes', 'title': 'Fixed times, free decisions', 'plate': plate(2, 'Process changes'),
      'deck': 'Three routes were tried. Only one keeps both the plan and the doctor’s call.'},
     {'type': 'maze', 'start': 'A day that feels too dynamic', 'goal': 'A plan that holds on a busy day',
      'routes': [{'kind': 'dead', 'name': 'Fix what gets decided', 'why': 'Who is fit to leave stays a clinical call. A rule on that would be broken every day.', 'point': 1},
                 {'kind': 'dead', 'name': 'No fixed times at all', 'why': 'Then nothing is ready the evening before. Every afternoon gets rebuilt, as it is today.', 'point': 2},
                 {'kind': 'way', 'name': 'Fix when decisions are made', 'why': 'The 2 PM mapping, the 5 PM check and the 6 PM freeze. What gets decided stays with the doctor.',
                  'needs': ['One fixed round at 5 PM', 'Doctors check a predicted date'], 'point': 3}],
      'sheets': [S('what', 'Ruled out', 'Fix what gets decided', 'A rule on who goes home would sit on top of a clinical call. Doctors would break it daily, and they would be right to.',
                   [('Why it fails', 'Clinical calls cannot be timetabled', 'outcome')]),
                 S('none', 'Ruled out', 'No fixed times at all', 'Without fixed times, nobody can plan the evening before. That is how the day runs now: rebuilt every afternoon.',
                   [('Why it fails', 'Nothing is ready the evening before', 'outcome')]),
                 S('when', 'The way through', 'Fix when decisions are made', 'The times are fixed. The decisions are not. A step-down that slips is an input to the next pass, not a breach.',
                   [('Fixed', 'When the 2 PM, 5 PM and 6 PM decisions happen', 'start'), ('Left alone', 'Who is fit to leave, emergencies, a step-down that slips')],
                   'Which decision moves most often at your hospital?')]},
     {'type': 'rerun', 'tries_label': 'Try a change', 'loop_label': 'What happens next',
      'tries': [{'title': 'An emergency arrives', 'point': 4}, {'title': 'A step-down slips a day', 'point': 4}, {'title': 'A patient stays one more night', 'point': 4}],
      'loop': [{'title': 'Something changes'}, {'title': 'The plan re-runs', 'line': 'Only for the beds it touches'},
               {'title': 'Call-in times re-issued', 'line': 'Only the affected patients hear'}, {'title': 'The change is recorded', 'line': 'A logged event, not a rule broken', 'state': 'outcome'}],
      'sheets': [S('er', 'A change', 'An emergency arrives', 'Emergencies arrive when they arrive. A bed is held back for them. The plan re-runs for the beds that move, and nothing else changes.',
                   [('What moves', 'One or two call-in times')], 'How many emergencies do you admit on a usual day?'),
                 S('step', 'A change', 'A step-down slips a day', 'The ICU patient stays another day. The next pass takes that in. The patient waiting for that bed gets a new call-in time.',
                   [('What moves', 'The bed it was meant to free')], 'How often does a step-down slip?'),
                 S('stay', 'A change', 'A patient stays one more night', 'The doctor decides the patient is not fit to leave. That is the doctor’s call. The plan follows it and records the change.',
                   [('What moves', 'One bed, one call-in time')], 'Who would tell the desk at your hospital?')]},
     {'type': 'effect', 'label': 'Your numbers are steady', 'value': '89% · 6.5 days · 41',
      'sub': 'Beds full, average stay and admissions a day. The 41 is worked out from your figures. No single bed is steady, but the total is.'}],
    acts('Next: part 3, the people and their buy-in', 'Yes, take me into part 3, the key people'),
    'The library maze, layered: two routes ruled out and the way through. Then the re-run loop: try a change and the plan runs again.'))

# ---------------------------------------------------------------------------------------------- 07 · transcript 26
T.append(turn(7, 26, '“Tell me more about why a Discharge Manager is needed”', 'No. tell me more about why it is needed',
    'Why the Discharge Manager exists, explained before it is priced. No rupee figure in the drawing: the role is priced in part 4. The close hands over to the next part by name.',
    {'text': ['Fair question. Here it is in one picture.'],
     'bullets': ['A discharge is not one job. It is a chain. Every step has someone. None of the gaps between them do.',
                 'So each step waits until somebody notices it. Whoever is free that day does the chasing.',
                 'That is why it hits your bed plan. Every time in the plan comes from a discharge time. With an owner, those become commitments.'],
     'pointer': 'Pick a gap to see who waits there. Then switch to the chain with an owner.',
     'invite': 'The role costs about ₹4 to 4.5 lakhs a year. We set it against the revenue in part 4. Next is part 3, the key people. Shall we go there?',
     'note': 'Nothing is broken. The waiting is in the gaps.',
     'points': pts('The gaps', 'Who chases today', 'What an owner does', 'A time you can trust'),
     'prompts': ['Yes, let us discuss the key people', 'Can someone we already have do this?', 'How is this different from a ward in charge?']},
    [{'type': 'heading', 'eyebrow': 'Part 2 · Process changes', 'title': 'The waiting is in the gaps', 'plate': plate(2, 'Process changes'),
      'deck': 'A discharge today, step by step. No step is broken. Nobody owns the gaps between them.'},
     {'type': 'gap-knots',
      'steps': [{'title': 'The doctor’s word', 'line': 'On the round'}, {'title': 'Ward and pharmacy', 'line': 'Medicines returned'},
                {'title': 'Bill and insurance', 'line': 'Final bill, then approval'}, {'title': 'Payment and exit', 'line': 'Briefing, then the patient leaves'},
                {'title': 'Bed cleaned and free', 'line': 'Hours after billing stopped'}],
      'gaps': [{'title': 'Who tells the ward?', 'point': 1}, {'title': 'Who starts the bill?', 'point': 1}, {'title': 'Who chases the insurer?', 'point': 2}, {'title': 'Who calls housekeeping?', 'point': 2}],
      'switch': {'today': 'Today', 'owner': 'With an owner', 'cap_today': 'Each gap waits until somebody notices it.', 'cap_owner': 'One owner chases every gap the moment it opens.'},
      'caption': 'No step is broken. The waiting is in the gaps, and nobody owns a gap.',
      'sheets': [S('g1', 'Gap 1', 'Who tells the ward?', 'The doctor has decided. The ward hears when someone passes it on. Until then nothing moves.',
                   [('Today', 'Whoever is free passes it on'), ('With an owner', 'Passed on the moment it is said', 'start')], 'How does the ward hear today?'),
                 S('g2', 'Gap 2', 'Who starts the bill?', 'Medicines are back, but billing waits to be told. The bill starts when someone notices.',
                   [('Today', 'Billing waits to be told'), ('With an owner', 'Started as the ward finishes', 'start')], 'Who tells billing at your hospital?'),
                 S('g3', 'Gap 3', 'Who chases the insurer?', 'The bill is sent for approval. Then it sits. Somebody chases it if they have time that day.',
                   [('Today', 'Chased if someone has time'), ('With an owner', 'Chased on a clock', 'start')], 'Who follows up with insurers today?'),
                 S('g4', 'Gap 4', 'Who calls housekeeping?', 'The patient has left. The bed waits until housekeeping hears. Billing on that bed stopped hours ago.',
                   [('Today', 'Called when someone notices'), ('With an owner', 'Called as the patient leaves', 'start')], 'How does housekeeping hear a bed is free?')]},
     {'type': 'notes', 'label': 'What an owner does',
      'items': [{'title': 'Sees one chain', 'text': 'Every discharge, from the doctor’s word to the free bed.', 'point': 3},
                {'title': 'Chases each gap', 'text': 'The moment it opens, not when someone notices.', 'point': 3},
                {'title': 'Gives a time you can trust', 'text': 'The bed plan is built on it.', 'point': 4}],
      'sheets': [S('chain', 'What an owner does', 'Sees one chain', 'Today each step belongs to a different team. The owner is the one person who sees the whole discharge.',
                   [('Reports to', 'The Head of Operations')]),
                 S('chase', 'What an owner does', 'Chases each gap', 'Nobody chases a gap today unless they are free. The owner chases every gap as it opens.',
                   [('Instead of', 'Whoever is free that day')]),
                 S('trust', 'What an owner does', 'Gives a time you can trust', 'Every time in the bed plan comes from a discharge time. With an owner, those times are commitments, not guesses.',
                   [('Changes', 'The plan is not rebuilt every afternoon', 'start')], 'How often is your bed plan rebuilt in a day?')]},
     {'type': 'effect', 'label': 'What the role changes', 'value': 'A time you can trust',
      'sub': 'A discharge time the bed side can plan on. Today those times are guesses, so the plan is rebuilt every afternoon.'}],
    acts('Next: part 3, the key people', 'Yes, let us discuss the key people'),
    'The library knots motif: a discharge chain whose waiting is in the gaps. Switch to an owner and the knots come undone. No rupee figure in the drawing.'))

# ---------------------------------------------------------------------------------------------- 08 · transcript 27
T.append(turn(8, 27, 'Part 3: Key people, rebuilt for both sides', 'yes, let us discuss about the Key People',
    'The version of record for part 3 (turn 24 was superseded). Six teams on the same footing, the reporting shape drawn: Head of Operations signs off, two managers as peers.',
    {'text': ['Six teams touch this, plus two managers and one person who signs it off.'],
     'bullets': ['Nobody’s job changes. What changes is when they confirm something the system has already worked out.',
                 'The resistance sits in one place. It is being asked to name a discharge date a day early. Show the doctor a date to check, and it holds.',
                 'Both managers report to the Head of Operations. It is the only level that can tell both sides to work to one plan.'],
     'pointer': 'Pick a team to see what changes for them.',
     'invite': 'Shall we move on to part 4, the teams and the numbers?',
     'note': 'Ask a doctor to check a date, not to produce one.',
     'points': pts('Doctors', 'Medical Supervisory', 'Admissions desk', 'Discharge team', 'Billing', 'Head of Operations'),
     'prompts': ['Yes, let us move on to part 4', 'What if the doctors still refuse?', 'Why not have one manager report to the other?']},
    [{'type': 'heading', 'eyebrow': 'Part 3 · People and buy-in', 'title': 'Six teams, one sign-off', 'plate': plate(3, 'People and buy-in'),
      'deck': 'Nobody’s job changes. Each team confirms something the system has already worked out.'},
     {'type': 'people', 'teams_label': 'The six teams, and what each one receives', 'resist_tag': 'Resistance sits here',
      'teams': [{'title': 'Doctors', 'gets': 'Speak on the round. Tap to confirm a predicted date.', 'resist': True, 'point': 1},
                {'title': 'Medical Supervisory', 'gets': 'One round at 5 PM, only for beds expected to free', 'point': 2},
                {'title': 'Admissions desk', 'gets': 'Told when to call each patient in', 'point': 3},
                {'title': 'Discharge team', 'gets': 'A release deadline for each bed, instead of a surprise', 'point': 4},
                {'title': 'Billing', 'gets': 'One new report: bill close and open, against the bed', 'point': 5},
                {'title': 'IT', 'gets': 'Read access to systems you already run, given once'}],
      'approver': {'tag': 'Sign-off', 'title': 'Head of Operations', 'line': 'Approves the new flows. Takes no part in the daily work.'},
      'managers': [{'tag': 'New role', 'title': 'Bed Manager', 'line': 'Runs tomorrow’s bed plan'}, {'tag': 'New role', 'title': 'Discharge Manager', 'line': 'Runs every discharge to the free bed'}],
      'tree_note': 'Same level, same size. Neither reports to the other.',
      'sheets': [S('doc', 'Doctors', 'Speak on the round', 'A spoken note on the round they already do. The system shows a predicted discharge date. The doctor confirms or corrects it with a tap.',
                   [('What is asked', 'A date a day early', 'target'), ('Extra time', 'None beyond the round', 'start')], 'Which doctors would you ask first?'),
                 S('ms', 'Medical Supervisory', 'One round at 5 PM', 'One fixed round, only for beds expected to free tomorrow. They confirm or correct by 5 PM, so the plan freezes at 6 PM.',
                   [('What changes', 'The time, not the job')], 'Who leads Medical Supervisory today?'),
                 S('desk', 'Admissions desk', 'Told when to call', 'The desk stops guessing. It is told when to call each patient in, bed by bed.',
                   [('What changes', 'Fewer calls, made at the right time', 'start')], 'Who runs your admissions desk today?'),
                 S('dis', 'Discharge team', 'A release deadline per bed', 'The discharge team gets a deadline for each bed it is releasing, instead of a surprise in the afternoon.',
                   [('What changes', 'A deadline they can plan to')], 'Who leads your discharge team today?'),
                 S('bill', 'Billing', 'One new report', 'Bill close and bill open, read against the same bed. Both facts already exist in your system.',
                   [('What changes', 'One report, run weekly')], 'Who runs billing reports today?'),
                 S('it', 'IT', 'Read access, once', 'Your IT team gives read access to the systems you already run. After that, nothing more is asked.',
                   [('What changes', 'One piece of work at the start')], 'Who in IT would we work with?')]},
     {'type': 'pair', 'items': [
        {'label': 'Where the resistance sits', 'value': 'A date a day early', 'state': 'target', 'point': 1,
         'sub': 'Naming a discharge date a day ahead is a clinical call. Checking a predicted date is not.', 'ask': {'label': 'Ask about this', 'say': 'What if the doctors still refuse?'}},
        {'label': 'Extra clinical time', 'value': 'None beyond the round', 'state': 'start',
         'sub': 'This claim is wrong if the round gets longer to give the date. We would measure that from the first week.'}]}],
    acts('Next: part 4, the teams and the numbers', 'Yes, let us move on to part 4'),
    'Six teams as rooms on one plan, the doctors’ room marked where the resistance sits. Then the sign-off tree: Head of Operations over two managers of the same size.'))

# ---------------------------------------------------------------------------------------------- 09 · transcript 28
T.append(turn(9, 28, 'Part 4: Teams and numbers, both sides', 'yes let us move on',
    'Four roles, two sizing chains: the admissions side settled on the hospital’s numbers, the discharge side waiting for its discharge pattern. Full cost, not extra cost, said plainly.',
    {'text': ['Four roles. Two managers, and two teams under them.'],
     'bullets': ['The admissions side we can settle. About 41 admissions a day, 5 an hour per person, over a short window. That gives 3 on the afternoon shift.',
                 'The discharge side we cannot settle yet. The usual rule of one person for 15 discharges a day gives 3. At another hospital the real answer was 2.',
                 'The cost shown is the full cost of these roles, not the extra cost. Send us four numbers and it becomes a difference.'],
     'pointer': 'Pick a role to open it. Move the slider to see how the busiest hour sets the number of staff. Type in any number you have.',
     'invite': 'Shall we finish with part 5, the measures?',
     'note': 'The busiest hour sets the number, not the daily average.',
     'points': pts('Bed Manager', 'Discharge Manager', 'Admissions Executives', 'Discharge Executives', 'The four numbers'),
     'prompts': ['Yes, let us do the measures', 'Here is our desk roster', 'Why not just use the usual rule?']},
    [{'type': 'heading', 'eyebrow': 'Part 4 · Teams and roles', 'title': 'Four roles, sized by the busiest hour', 'plate': plate(4, 'Teams and roles'),
      'deck': 'Two managers and two teams. One side is settled on your numbers. The other waits for one more.'},
     {'type': 'sizing', 'roles_label': 'The four roles', 'new_tag': 'New role',
      'roles': [{'title': 'Bed Manager', 'line': 'Owns tomorrow’s bed plan. About ₹4 to 4.5 lakhs a year.', 'new': True, 'point': 1},
                {'title': 'Discharge Manager', 'line': 'Owns every discharge. About ₹4 to 4.5 lakhs a year.', 'new': True, 'point': 2},
                {'title': 'Admissions Executives', 'tag': 'Team', 'line': 'Three on the afternoon shift. About ₹3 to 3.5 lakhs each.', 'point': 3},
                {'title': 'Discharge Executives', 'tag': 'Team', 'line': 'Number not settled yet, so not in the cost.', 'point': 4}],
      'chains': [{'title': 'Admissions side', 'verdict': 'Settled', 'state': 'outcome',
                  'steps': [{'title': 'About 41 admissions a day', 'line': 'Worked out from your figures'},
                            {'title': 'One person handles 5 an hour', 'slider': {'label': 'Arrivals in your busiest hour', 'min': 5, 'max': 25, 'value': 15, 'per': 5, 'unit': 'people on the shift', 'source': 'Tojo’s guess'}},
                            {'title': '3 on the afternoon shift', 'line': 'The busiest hour sets it, not the daily average', 'state': 'outcome'}]},
                 {'title': 'Discharge side', 'verdict': 'Waiting on you', 'state': 'target',
                  'steps': [{'title': 'Usual rule: 1 per 15 a day', 'line': 'Gives 3 for about 41 discharges'},
                            {'title': 'Another hospital: really 2', 'line': 'Their two busy windows changed the answer'},
                            {'title': 'Your discharge pattern', 'state': 'target', 'line': 'When your discharges happen through the day', 'result': 'Type it into the list below'}]}],
      'caption': 'We used the usual rule at another hospital. Their real answer was 2, so we will not apply it here blind.',
      'sheets': [S('bm', 'New role', 'Bed Manager', 'Owns the whole bed plan as one person. The role is about coordination, so it is not sized per admission.',
                   [('Cost', 'About ₹4 to 4.5 lakhs a year'), ('Reports to', 'The Head of Operations')], 'Is anyone doing this job today?'),
                 S('dm', 'New role', 'Discharge Manager', 'Owns every discharge as one chain. A peer of the Bed Manager, not under them.',
                   [('Cost', 'About ₹4 to 4.5 lakhs a year'), ('Reports to', 'The Head of Operations')], 'Is anyone doing this job today?'),
                 S('ae', 'Team', 'Admissions Executives', 'Sized by the busiest hour. Your patients arrive over a short window, so the peak sets the number.',
                   [('Number', '3 on the afternoon shift', 'outcome'), ('Cost', 'About ₹3 to 3.5 lakhs each')], 'How many people sit on your desk each shift?'),
                 S('de', 'Team', 'Discharge Executives', 'Not settled. We need to know when your discharges actually happen through the day.',
                   [('Number', 'Waiting on your discharge pattern', 'target')], 'When are your two busiest discharge hours?')]},
     {'type': 'costing', 'cost_label': 'What we can cost, a year', 'cost': '₹17 to 19.5 lakhs',
      'lines': [{'label': 'Two managers', 'value': '₹8 to 9 lakhs'}, {'label': 'Three Admissions Executives', 'value': '₹9 to 10.5 lakhs'}],
      'note': 'The full cost of these roles, not the extra cost. Discharge Executives are left out, not guessed.',
      'needed_label': 'Still needed from you',
      'needed': [{'label': 'Desk roster per shift, both sides', 'hint': 'For example, 2 morning, 2 evening, 1 night'},
                 {'label': 'Arrivals hour by hour', 'hint': 'Or just your busiest two hours'},
                 {'label': 'Bed transfers inside the hospital a day', 'hint': 'A rough number is fine'},
                 {'label': 'When discharges happen through the day', 'hint': 'For example, most between 11 AM and 3 PM'}]}],
    acts('Next: part 5, what to measure', 'Yes, let us do the measures'),
    'The four roles, then the two sizing chains with a live slider on the busiest hour. The discharge chain and the four missing numbers take entries in place.'))

# ---------------------------------------------------------------------------------------------- 10 · transcript 29
T.append(turn(10, 29, 'Part 5: What to measure', 'yes let us do the KPIs',
    'Eight measures, not eighteen. Six new, two already tracked and not expected to move. Three are early warnings. Nobody measures what nobody owns.',
    {'text': ['Eight numbers, checked weekly. Six of them nobody measures today.'],
     'bullets': ['Start with dead bed time. It moves when any of the others improve. Nothing in your hospital produces it today.',
                 'Three of the eight are early warnings. They show whether people are doing the new thing. If they slip, the rest follows within two weeks.',
                 'Weekly, not monthly. A month hides a bad week. Occupancy and length of stay stay as they are. This work is not meant to move them.'],
     'pointer': 'Pick a dial to open it. Filter to the early warnings to see the three to watch first.',
     'invite': 'That is all five parts. Do you want a short summary, or shall we talk about a first step?',
     'note': 'Nobody measures what nobody owns.',
     'points': pts('Dead bed time', 'Beds mapped by 6 PM', 'Discharge signals on time', 'Admissions by noon', 'Occupancy and stay'),
     'prompts': ['Yes, give me a summary', 'What would a first step look like?', 'Who would read these each week?']},
    [{'type': 'heading', 'eyebrow': 'Part 5 · Measures', 'title': 'Eight dials, six of them new', 'plate': plate(5, 'Measures'),
      'deck': 'Checked weekly. The dashed dials have no needle, because nobody reads them today.'},
     {'type': 'gauges', 'filters': {'all': 'All eight', 'lead': 'Early warnings', 'result': 'Results'}, 'key_line': 'Dashed dials: nobody measures these today.',
      'new_tag': 'New', 'tracked_tag': 'Tracked',
      'measures': [{'title': 'Dead bed time', 'reading': 'Hours from one bill closing to the next opening, per bed', 'kind': 'result', 'new': True, 'point': 1},
                   {'title': 'Time to a bed', 'reading': 'Arrival to bed, against under 30 minutes', 'kind': 'result', 'new': True},
                   {'title': 'Beds mapped by the 6 PM freeze', 'reading': 'Share of planned admissions with a bed', 'kind': 'lead', 'new': True, 'point': 2},
                   {'title': 'Discharge signals on time', 'reading': 'Given a full day ahead', 'kind': 'lead', 'new': True, 'point': 3},
                   {'title': 'Admissions finished by noon', 'reading': 'Share of the day’s admissions', 'kind': 'lead', 'new': True, 'point': 4},
                   {'title': '2 PM plans that hold', 'reading': 'Share unchanged at the 6 PM freeze', 'kind': 'result', 'new': True},
                   {'title': 'Beds full', 'reading': '89% today. Not expected to move.', 'kind': 'result', 'needle': 0.89, 'point': 5},
                   {'title': 'Average stay', 'reading': '6.5 days. May come down a little.', 'kind': 'result', 'needle': 0.65, 'point': 5}],
      'caption': 'Nobody measures what nobody owns. The two managers each own a set.',
      'sheets': [S('dbt', 'Result · new', 'Dead bed time', 'The one number that moves when any of the others improve. Both halves already sit in your billing system. Only the link to the bed is missing.',
                   [('Owned by', 'The Bed Manager'), ('Data', 'Bill close and bill open, against the bed')], 'Has anyone ever measured this at your hospital?'),
                 S('tat', 'Result · new', 'Time to a bed', 'From the patient arriving to the patient in a bed. Paperwork is the only step that cannot be made shorter.',
                   [('Owned by', 'The Bed Manager'), ('Goal', 'Under 30 minutes', 'target')], 'How do you time admissions now?'),
                 S('map', 'Early warning · new', 'Beds mapped by the 6 PM freeze', 'Of tomorrow’s planned admissions, how many have a bed by 6 PM. If this slips, the call-in times slip next.',
                   [('Owned by', 'The Bed Manager')], 'How many planned admissions do you have on a usual day?'),
                 S('sig', 'Early warning · new', 'Discharge signals on time', 'How many discharges were signalled a full day ahead. This is the doctors’ part of the plan.',
                   [('Owned by', 'The Discharge Manager')], 'How early do doctors say who goes home now?'),
                 S('noon', 'Early warning · new', 'Admissions finished by noon', 'How many of the day’s admissions are in a bed by noon, instead of 4:30 to 8 PM.',
                   [('Owned by', 'The Bed Manager'), ('Today', 'Most after 4:30 PM', 'outcome')], 'What share is done by noon today?'),
                 S('hold', 'Result · new', '2 PM plans that hold', 'How many 2 PM mappings are still the same at the 6 PM freeze. It shows how good the first pass is.',
                   [('Owned by', 'The Bed Manager')]),
                 S('occ', 'Result · tracked', 'Beds full', 'You track this already. It stays as it is. This work is not meant to raise it.',
                   [('Today', '89%'), ('Expected', 'No change')]),
                 S('alos', 'Result · tracked', 'Average stay', 'You track this already. It may come down a little. That gain is counted once, inside the money.',
                   [('Today', '6.5 days'), ('Expected', 'A little lower')])]},
     {'type': 'effect', 'label': 'The one to start with', 'value': 'Dead bed time',
      'sub': 'Both halves already sit in your billing system. Only the link to the bed is missing.'}],
    acts('Next: a short summary of all five parts', 'Yes, give me a summary'),
    'Eight measures as drafting dials: six dashed with no needle, two with a needle at the hospital’s own figures. Filter to the three early warnings.'))

# ---------------------------------------------------------------------------------------------- 11 · transcript 30
T.append(turn(11, 30, 'The summary', 'yes give me a summary',
    'The approved summary: facts muted because they are the hospital’s, the five parts as pieces, worth beside cost with no ratio stated, the four numbers that would finish it.',
    {'text': ['Here is the whole thing on one page.'],
     'bullets': ['Everything we found is yours. One team does both jobs, one after the other. Patients reach a bed between 4:30 and 8 PM.',
                 'The gain is ₹1.5 to 2 crore a year. We used your ₹8,000 per bed a day. Your total daily revenue says it should be higher.',
                 'The cost is ₹17 to 19.5 lakhs a year. The Discharge Executives are not in that yet.'],
     'pointer': 'Pick a finding, a piece or a box to open it.',
     'invite': 'Occupancy will not go up. The shorter stay is already inside the gain, counted once. Shall we talk about a first step?',
     'note': 'Your facts, five parts, worth beside cost.',
     'points': pts('What we found', 'The five parts', 'What it is worth', 'What it costs', 'The four numbers'),
     'prompts': ['Ok, proceed to a first step', 'Why should the gain be higher?', 'Which part would you start with?']},
    [{'type': 'heading', 'eyebrow': 'The summary', 'title': 'The whole thing on one page', 'deck': 'Your facts first, then the five parts, then worth beside cost.'},
     {'type': 'findings', 'label': 'What we found: your facts, not ours',
      'items': [{'tag': 'One team', 'value': 'Both jobs in turn', 'line': 'Discharges first, then admissions', 'point': 1},
                {'tag': 'Into a bed', 'value': '4:30 to 8 PM', 'line': 'Patients arrive at about 1 PM', 'point': 1},
                {'tag': 'Between two bills', 'value': '4 to 5 hours', 'line': 'Each bed earns nothing in that time', 'point': 1}],
      'caption': 'Muted, because they are yours. Nothing in this row is our proposal.',
      'sheets': [S('team', 'Your answer', 'One team, both jobs', 'You told us one team runs discharges and admissions. Its own clock times showed them running one after the other.',
                   [('Found in', 'Diagnosis')]),
                 S('bed', 'Your times', 'A bed only after 4:30 PM', 'Patients arrive at about 1 PM. They reach a bed between 4:30 and 8 PM.',
                   [('Found in', 'Diagnosis')]),
                 S('gap', 'Your billing', '4 to 5 hours between bills', 'From one patient’s bill closing to the next patient’s bill opening on the same bed. Up to 8 hours on a bad day.',
                   [('Found in', 'Diagnosis')])]},
     {'type': 'jigsaw', 'hint': 'Pick a piece. The pieces it relies on are outlined.',
      'pieces': [{'label': 'Part 1', 'when': 'Part 1', 'title': 'Automations', 'line': 'One engine on data you already hold', 'relies_on': [3], 'point': 2},
                 {'label': 'Part 2', 'when': 'Part 2', 'title': 'Process changes', 'line': 'Both jobs run together', 'relies_on': [3], 'point': 2},
                 {'label': 'Part 3', 'when': 'Part 3', 'title': 'People and buy-in', 'line': 'The Head of Operations signs it off', 'point': 2},
                 {'label': 'Part 4', 'when': 'Part 4', 'title': 'Teams and roles', 'line': 'Two managers, two teams', 'relies_on': [2], 'point': 2},
                 {'label': 'Part 5', 'when': 'Part 5', 'title': 'Measures', 'line': 'Eight numbers, checked weekly', 'relies_on': [4], 'point': 2},
                 {'label': 'What it is for', 'when': 'The gain', 'title': 'Bills start hours earlier', 'line': 'On every bed that changes patient', 'relies_on': [1, 2, 4], 'point': 3}],
      'condition': 'Take any piece away and the gain does not arrive.',
      'sheets': [S('a', 'Part 1', 'Automations', 'Six steps from one engine, reading data you already hold. Needs read access and discharge automated first.'),
                 S('p', 'Part 2', 'Process changes', 'Admissions and discharges run together. Four smaller changes and two owners hold it up.'),
                 S('k', 'Part 3', 'People and buy-in', 'Six teams confirm what the system worked out. The Head of Operations approves the flows.'),
                 S('t', 'Part 4', 'Teams and roles', 'Two managers, three Admissions Executives settled, Discharge Executives waiting on your pattern.'),
                 S('m', 'Part 5', 'Measures', 'Eight numbers weekly. Six new, three of them early warnings. Dead bed time first.'),
                 S('g', 'What it is for', 'Bills start hours earlier', 'Each bed earns from earlier in the day. That is where the ₹1.5 to 2 crore comes from. The operation theatre is left out.',
                   [('Not counted', 'Occupancy. It does not go up.')])]},
     {'type': 'pair', 'items': [
        {'label': 'What it is worth', 'value': '₹1.5 to 2 crore', 'state': 'start', 'point': 3,
         'sub': 'A year, from earlier billing on your beds. Worked out from your figures. The operation theatre is left out.'},
        {'label': 'What it costs', 'value': '₹17 to 19.5 lakhs', 'point': 4,
         'sub': 'A year, for the two managers and three Admissions Executives. Discharge Executives are not in yet.'}],
      'caption': 'Four numbers would finish the picture: the desk roster, hourly arrivals, bed transfers inside the hospital, and when discharges happen.'}],
    acts('Next: what a first step looks like', 'Ok, proceed'),
    'Muted findings, the five parts as one jigsaw ending in the gain, and worth beside cost with no ratio stated: you draw the comparison.'))

# ---------------------------------------------------------------------------------------------- 12 · transcript 31
T.append(turn(12, 31, 'What a first step looks like', 'ok proceed',
    'Four steps; nothing changes for staff until step 3, so steps 1 and 2 are muted. The exit at step 2 is the load-bearing offer. Discharge before bed mapping, because the files make it a prerequisite.',
    {'text': ['There are four steps. Your day does not change until the third one.'],
     'bullets': ['Step 1 is read access. Your IT team connects us to the systems you already run. About two weeks.',
                 'Step 2 is measuring what happens now. Four weeks of real numbers, and nobody works differently.',
                 'Step 3 is where the day changes. Step 4 is the build: discharge first, then the bed mapping on top.'],
     'pointer': 'Pick a step to open it. The doors at the end lead into how it is built and how the day changes.',
     'invite': 'At the end of step 2 you have your own dead bed time, not our guess. To start we need read access from IT, and one name from you.',
     'note': 'You find out if we were wrong before you spend anything.',
     'points': pts('Read access', 'Measuring now', 'The day changes', 'The build', 'One name from you'),
     'prompts': ['How would the build work?', 'Who should own this until the managers are in?', 'Can we skip straight to step 3?']},
    [{'type': 'heading', 'eyebrow': 'The first step', 'title': 'Nothing changes until step three', 'deck': 'Steps 1 and 2 are muted. Nobody on your staff works differently in them.'},
     {'type': 'route', 'hint': 'Pick a step to open it.',
      'steps': [{'title': 'Read access', 'what': 'IT connects us to the systems you already run', 'muted': True, 'point': 1},
                {'title': 'Measure what happens now', 'what': 'Dead bed time per bed, the five admission steps', 'muted': True, 'point': 2},
                {'title': 'The day changes', 'what': 'Both jobs run together. Call-in times go out per bed', 'point': 3},
                {'title': 'The build', 'what': 'Discharge first, then the bed mapping on top', 'point': 4}],
      'sheets': [S('s1', 'About two weeks', 'Read access', 'Your IT team connects us to the systems you already run. We read, we write nothing back.',
                   [('Changes for staff', 'Nothing'), ('Needs', 'Read access from IT', 'target')], 'Who in IT would give us access?'),
                 S('s2', 'Four weeks', 'Measure what happens now', 'Dead bed time on each bed, and the five admission steps. Real numbers, and nobody works differently.',
                   [('Changes for staff', 'Nothing'), ('You get', 'Your own dead bed time', 'start')], 'Which ward would you start measuring?'),
                 S('s3', 'After step 2', 'The day changes', 'The two jobs start running together. Call-in times go out bed by bed.',
                   [('Changes for staff', 'The order of the day')]),
                 S('s4', 'After step 3', 'The build', 'Discharge first, because the bed plan runs on its times. Then the bed mapping on top.',
                   [('Order', 'Discharge, then beds'), ('Why', 'The bed plan needs real discharge times')])],
      'fork': {'question': 'At the end of step 2 you have your own dead bed time. Where next?',
               'options': [{'tab': 'Automations', 'label': 'How the build works', 'what': 'Read access, the engine, discharge first', 'say': 'How would the build work?'},
                           {'tab': 'Processes', 'label': 'How the day changes', 'what': 'Both jobs together, the 5 PM round', 'say': 'Show me how the day would change'}]}},
     {'type': 'notes',
      'items': [{'title': 'What we need to start', 'text': 'Read access from IT. One name from you to own this.', 'point': 5, 'state': 'target'},
                {'title': 'What you have after step 2', 'text': 'Your own dead bed time. Not our guess at it.', 'point': 2}],
      'caption': 'If it is smaller than we said, you know before you spend anything on people or process.',
      'sheets': [S('need', 'To start', 'What we need to start', 'Two things. Read access from your IT team. And one name from you to own this until the managers are in place.',
                   [('From IT', 'Read access'), ('From you', 'One name', 'target')], 'Who would own this at your hospital?', 'A name or a role'),
                 S('have', 'After step 2', 'What you have after step 2', 'Your own dead bed time, measured on your beds. If it is smaller than we said, you can stop there.',
                   [('Costs you', 'Nothing in people or process', 'start')])]}],
    acts('Next: how the build works, in Automations', 'How would the build work?'),
    'The library route: four stations, the first two muted where nothing changes for staff. At the end, doors into Automations and Processes.'))

for t in T:
    note = t.pop('_note')
    json.dump(t, open(os.path.join(HERE, '%s.json' % t['turn']['id']), 'w', encoding='utf-8'), ensure_ascii=False, indent=1)
    t['_note'] = note
man = {'place': 'Solutions', 'tool': 'Bed Management', 'turns': [{'file': 'bm-so-01-A.json', 'note': 'Transcript turn 18 · the automation part. Sample A (six switches, one bulb), approved 1 Oct.'}] +
       [{'file': '%s.json' % t['turn']['id'], 'note': t['_note']} for t in T]}
json.dump(man, open(os.path.join(HERE, 'turns.json'), 'w', encoding='utf-8'), ensure_ascii=False, indent=1)
print('wrote bm-so-02 .. bm-so-12 and turns.json')
