"""Writes the Bed Management Automations turns after bm-au-01 (bm-au-02 to bm-au-07) and turns.json.

bm-au-01 is Sample B (approved 1 Oct 2026; A and C kept as templates). The record stops at transcript turn 31, so these
turns follow the prompts of the turn before. Content comes only from bed-management.md §7.4.1 (the engine, a to e, the
2 PM and 6 PM passes, Admission TAT under 30 minutes, admitted by about noon), §7.4.2 (read access, IP extraction, the
billing join, the admissions desk link), §7.2 and the transcript's Nagpur facts (turns 19, 20, 31). Figures that are a goal
or Tojo's own are labelled as such. Automations ends before process changes, people, team changes or KPIs are detailed:
bm-au-07 only mentions them, in its prompts and the jump to Processes (Avishek, 1 Oct).
Draw with: python ../../automations-html-generator/bm_automations_html.py build"""
import copy, json, os
HERE = os.path.dirname(os.path.abspath(__file__))

def S(key, when, title, text, lines=(), entry=None, hint=None, hand=None, ask=None):
    s = {'key': key, 'when': when, 'title': title, 'text': text}
    if lines: s['lines'] = [dict(zip(('label', 'value', 'state'), l)) for l in lines]
    if entry: s['entry'] = entry
    if hint: s['entry_hint'] = hint
    if hand: s['hand'] = {'who': hand[0], 'does': hand[1]}
    if ask: s['ask'] = {'label': ask[0], 'say': ask[1]}
    return s

JUMP = {'tab': 'Processes', 'detail': 'How the day changes on the wards', 'say': 'Take me to Processes'}

def turn(n, msg, context, text, bullets, invite, points, prompts, pointer, eyebrow, plate, title, deck, block, effect, go, add, note=None):
    s = {'turn': {'id': 'bm-au-%02d' % n, 'tab': 'Automations', 'type': 'part', 'register': 'advisory', 'tool': 'Bed Management', 'user_message': msg,
                  'context': context, 'transcript': {'label': 'After transcript turn 31 · Automations, turn %d (the record stops at 31)' % n}},
         'chat': {'text': text, 'bullets': bullets, 'invite': invite, 'points': [{'n': i + 1, 'label': x, 'canvas': True} for i, x in enumerate(points)],
                  'prompts': prompts, 'pointer': pointer},
         'canvas': {'blocks': [{'type': 'heading', 'eyebrow': eyebrow, 'plate': {'tag': 'Automations', 'name': plate, 'stage': 'Idea'}, 'title': title, 'deck': deck},
                               block, dict({'type': 'effect'}, **effect)],
                    'actions': {'go': {'detail': go[0], 'say': go[1]}, 'add': {'detail': add[0], 'say': add[1]}, 'jump': copy.deepcopy(JUMP)}}}
    if note: s['chat']['note'] = note
    return s

T = []
# ---------------------------------------------------------------------------------------------- 02 · what IT does (helper)
T.append(turn(2, 'What exactly would our IT team do?',
    'From bed-management.md §7.2 (read access) and §7.4.2 (IP extraction, the bill-close and bill-open join, the admissions desk link), with transcript 19 and 20.',
    ['Your IT team gives five things. Four are read access or a report. One is a link at the admissions desk.'],
    ['Read access to admissions, discharges and the bed board. Your systems already hold these.',
     'Inpatient notes, pulled out. This lets the engine see who is near the usual stay for their procedure.',
     'One billing report. It sets bill close against bill open on the same bed. That gives dead bed time.'],
    'Tell me which systems you run, and I will name the exact asks.',
    ['Admissions and discharges', 'Inpatient notes', 'Billing report', 'Admissions desk link'],
    ['Why must discharge be built first?', 'What if some records are on paper?', 'What does Tojo build itself?'],
    'Pick an ask to see why it is needed and who in IT does it.',
    'Automations · your IT team', 'The IT links', 'Five asks, nothing written back', 'Each ask is read access or a report. Your teams keep working in the systems they have.',
    {'type': 'helper', 'hint': 'Pick an ask to see why it is needed and who in IT does it.', 'says': 'These are the five things I would ask your IT team for. Each one only reads. Nothing is written back to your systems.',
     'label': 'What I ask your IT team',
     'asks': [{'title': 'Read access to admissions and discharges', 'who': 'Your IT team, once', 'tag': 'Needed', 'tag_state': 'needed', 'point': 1},
              {'title': 'Inpatient notes, pulled out', 'who': 'Your IT team, once', 'tag': 'Needed', 'tag_state': 'needed', 'point': 2},
              {'title': 'Read access to the bed board', 'who': 'Your IT team, once', 'tag': 'Needed', 'tag_state': 'needed'},
              {'title': 'One billing report, bill to bill', 'who': 'Billing, with IT', 'tag': 'A report', 'tag_state': 'waiting', 'point': 3},
              {'title': 'A live link at the admissions desk', 'who': 'IT, with the admissions desk', 'tag': 'Later', 'tag_state': 'waiting', 'point': 4}],
     'park': 'We bring the rest ourselves: voice notes on rounds, reading OPD prescriptions and timing each admission step. Your IT team does none of these.',
     'sheets': [S('adt', 'Read access · once', 'Admissions and discharges', 'The engine reads who came in, who left, which bed and when. It is the record five of the engine’s jobs start from.',
                  [('Who does it', 'Your IT team'), ('It writes back', 'Nothing', 'start')], 'Which system holds admissions and discharges today?', 'For example, the hospital system'),
                S('ip', 'Pulled out · once', 'Inpatient notes', 'The stay so far for each patient. Without it the engine sees only who came and went, not who is near the usual stay.',
                  [('Who does it', 'Your IT team'), ('Used for', 'Predicting who frees a bed')], 'Are inpatient notes kept on a system?'),
                S('bed', 'Read access · once', 'The bed board', 'Which beds are empty, being cleaned or ready. The engine checks it against what the wards say.',
                  [('Who does it', 'Your IT team'), ('Used for', 'Checking a bed is really free')], 'How does your desk see bed status today?'),
                S('bill', 'A report · once', 'One billing report, bill to bill', 'Both times already sit in your billing system. The report joins them against the same bed. That gives dead bed time, bed by bed.',
                  [('Who does it', 'Billing, with IT'), ('It is', 'A report, not new records', 'start')], 'Which billing system do you run?'),
                S('desk', 'A link · later', 'A live link at the admissions desk', 'When a planned patient completes formalities, the desk sees a free mapped bed. Once a date is set, it shows on the bed plan with a bed number.',
                  [('Who does it', 'IT, with the admissions desk'), ('Comes', 'After the bed map is built')], 'How does your admissions desk book a planned patient today?')]},
    {'label': 'Written back to your systems', 'value': 'Nothing', 'state': 'start', 'sub': 'Every link only reads. Your records stay as they are, and your teams keep working in them.'},
    ('Next: why discharge comes first', 'Why must discharge be built first?'), ('Tell me what systems you run', 'Our IT team runs these systems: '),
    note='Read access and one report. We build everything else.'))

# ---------------------------------------------------------------------------------------------- 03 · discharge first (relay)
T.append(turn(3, 'Why must discharge be built first?',
    'From bed-management.md §7.4.1 (c) the discharge linkage as a double control and (e) call-in timing, and §7.4.2 (discharge is a prerequisite), with the Nagpur bill and dead bed time figures.',
    ['The bed plan runs on discharge times. If those times are guesses, the plan is a guess too.'],
    ['Discharge is built first so its times are real. They are logged as they happen, not reported later.',
     'The bed side then works backwards. It calls each patient in to arrive as their bed frees.',
     'Once linked, each side checks the other. A reported time that does not match the bed shows at once.'],
    'Tell me how a discharge is confirmed on your wards today.',
    ['Discharge confirmed', 'Patient called in'],
    ['How does it know which beds will free up?', 'What if some records are on paper?', 'What happens after the 6 PM freeze?'],
    'Switch between today and both sides linked. Pick a step to open it.',
    'Automations · the hand-over', 'Discharge, then beds', 'One hand-over, two sides', 'Discharge hands the bed over. The bed side can only plan on times that are real.',
    {'type': 'relay', 'hint': 'Pick a step of the hand-over. Switch to see it with both sides linked.', 'with_label': 'Both sides linked', 'lane_dis': 'The discharge side', 'lane_bed': 'The bed side',
     'gap': {'label': 'Dead bed time', 'today': '4 to 5 hours, yours', 'with': 'Shrinks from both ends'},
     'legs': [{'side': 'dis', 'who': 'Treating doctor', 'name': 'Discharge confirmed', 'today': 'Said on rounds', 'with': 'Logged the moment it is confirmed', 'point': 1},
              {'side': 'bed', 'who': 'Bed engine', 'name': 'Bed marked as freeing', 'today': 'Seen once the patient leaves', 'with': 'Seen hours before', 'checked': True},
              {'side': 'dis', 'who': 'Billing', 'name': 'Final bill closed', 'today': 'Around 12 to 1 PM', 'with': 'Time held against the bed'},
              {'side': 'bed', 'who': 'Bed engine', 'name': 'Next patient called in', 'today': 'After the bed is free', 'with': 'To arrive as it frees', 'point': 2, 'checked': True},
              {'side': 'bed', 'who': 'Admissions desk', 'name': 'First bill opened', 'today': 'From 5 PM, up to 8', 'with': 'Goal: around noon'}],
     'condition': 'Each side checks the other. If a reported discharge time does not match the bed, both teams see it.',
     'sheets': [S('conf', 'Discharge side', 'Discharge confirmed', 'Today the doctor says it on rounds. Once built, the time is logged when it is confirmed. That is the first time the bed side can trust.',
                  [('Today', 'Said on rounds'), ('Once built', 'Logged as it happens', 'target')], 'How is a discharge confirmed on your wards today?'),
                S('free', 'Bed side', 'Bed marked as freeing', 'The engine marks the bed as freeing as soon as discharge is confirmed. It checks the real time later against the bed.',
                  [('Checks', 'Reported time against the bed'), ('Shows', 'Any time that does not match')], 'Who tells the desk a bed is freeing today?'),
                S('bill', 'Discharge side', 'Final bill closed', 'Your bill closes around 12 to 1 PM. Once built, that time is held against the bed, not only the patient.',
                  [('Today', 'Around 12 to 1 PM', 'start'), ('Starts', 'Dead bed time')], 'What holds up the final bill most often?'),
                S('call', 'Bed side', 'Next patient called in', 'The engine works back from when the bed will be free. It sets a call-in time so the patient arrives as it frees.',
                  [('Needs', 'Real discharge times'), ('Makes', 'One call-in time per bed', 'target')], 'Who calls planned patients in today?',
                  hand=('the admissions desk', 'Calls each patient at their time.')),
                S('open', 'Bed side', 'First bill opened', 'Your first bill on the bed opens at 5 PM, up to 7 to 8 PM. The goal is around noon, once patients are called in on time.',
                  [('Today', 'From 5 PM, up to 7 to 8 PM', 'start'), ('Goal', 'Around noon', 'target')], 'When does a new patient’s first bill usually open?')]},
    {'label': 'Dead bed time today', 'value': '4 to 5 hours', 'state': 'start', 'sub': 'Your figure, up to 8 at worst. Discharge shrinks the front end. Call-in times shrink the back end.'},
    ('Next: how it knows which beds free up', 'How does it know which beds will free up?'), ('Tell me how discharge runs now', 'Today our discharges run like this: ')))

# ---------------------------------------------------------------------------------------------- 04 · predicting beds (agent)
T.append(turn(4, 'How does it know which beds will free up?',
    'From bed-management.md §7.4.1 (a) and (b): beds likely to free from patients near the usual stay for their procedure, and §7.4.2 (the 24-hour and 1 PM signals, the 5 PM confirmation).',
    ['It reads the stay so far for each patient. Then it sets it against similar past patients.'],
    ['Patients near the usual stay for their procedure are flagged. Nobody has to say it out loud first.',
     'Before the round, the doctor gets a short summary for each patient. It holds a predicted date.',
     'The doctor confirms or corrects it by 5 PM. The engine only predicts. The doctor decides.'],
    'Tell me which procedures fill most of your beds. That sets how fine the prediction can be.',
    ['Near the usual stay', 'Similar past patients', 'The doctor’s summary'],
    ['What if some records are on paper?', 'What happens after the 6 PM freeze?', 'Which automation do we switch on first?'],
    'Pick a step. The loop lights where the engine is.',
    'Automations · the prediction', 'The prediction', 'It predicts, the doctor decides', 'One patient through one day. Five steps, and the doctor has the last word.',
    {'type': 'agent', 'hint': 'Pick a step. The loop lights where the engine is, and its sheet opens.', 'loop': [{'id': 'n', 'name': 'Notice'}, {'id': 'g', 'name': 'Gather'}, {'id': 'c', 'name': 'Check'}, {'id': 'd', 'name': 'Draft'}, {'id': 'a', 'name': 'Ask'}],
     'steps': [{'when': 'Through the day', 'title': 'Spots patients near their usual stay', 'stages': ['n'], 'point': 1},
               {'when': 'Before rounds', 'title': 'Gathers notes and the stay so far', 'stages': ['g']},
               {'when': 'Before rounds', 'title': 'Checks against similar past patients', 'stages': ['c'], 'point': 2},
               {'when': 'On the round', 'title': 'Hands the doctor a summary to confirm', 'stages': ['d', 'a'], 'point': 3},
               {'when': 'By 5 PM', 'title': 'Takes the answer into tomorrow’s map', 'stages': ['a', 'n']}],
     'caption': 'The engine predicts. The doctor decides. Every predicted date goes to a doctor to confirm or correct.',
     'steps_label': 'One patient, one day',
     'never_label': 'What it never does',
     'never': ['It never decides a discharge.', 'It never calls a patient in on a date nobody confirmed.', 'It never changes your records.'],
     'sheets': [S('near', 'Through the day', 'Spots patients near their usual stay', 'Each procedure has a usual stay in your own past records. Patients close to it are flagged, ward and ICU alike.',
                  [('Reads', 'Inpatient notes, past stays'), ('Flags', 'Ward and ICU patients')], 'Which procedures fill most of your beds?'),
                S('gather', 'Before rounds', 'Gathers notes and the stay so far', 'The engine pulls together the notes, tests and days so far. The doctor does not have to look them up.',
                  [('Reads', 'Inpatient notes, voice notes')], 'What does a doctor check before saying a patient can go?'),
                S('check', 'Before rounds', 'Checks against similar past patients', 'The stay is set against past patients with the same procedure. The engine sets a likely date and how sure it is.',
                  [('Needs', 'Enough past cases per procedure'), ('Makes', 'A likely date', 'target')], 'How many years of past admissions are on your system?'),
                S('draft', 'On the round', 'Hands the doctor a summary to confirm', 'Ward patients need a signal a day ahead. ICU patients need theirs by 1 PM. The summary makes that a quick yes or no.',
                  [('Ward', '24 hours ahead'), ('ICU', 'By 1 PM')], 'Do your doctors give a likely discharge date today?',
                  hand=('the treating doctor', 'Confirms or corrects the date, by voice or a tap.')),
                S('take', 'By 5 PM', 'Takes the answer into tomorrow’s map', 'Every answer goes into tomorrow’s bed map. A corrected date moves the bed, and the call-in time with it.',
                  [('Feeds', 'The 6 PM freeze', 'start')], 'Who should hear when a date is corrected?')]},
    {'label': 'Signal needed', 'value': 'A day ahead', 'state': 'target', 'sub': 'Ward patients need a discharge signal 24 hours ahead. ICU patients need theirs by 1 PM.'},
    ('Next: what if records are on paper', 'What if some records are on paper?'), ('Tell me how rounds run now', 'Our evening rounds run like this: ')))

# ---------------------------------------------------------------------------------------------- 05 · paper (sources) · the night theme begins
T.append(turn(5, 'What if some records are on paper?',
    'From transcript 20 (we bring this, this has to be there, and “if almost nothing is digital”) and bed-management.md §7.2 and §7.4.2.',
    ['Some paper is fine. What we bring already reads from people, not from systems.'],
    ['OPD advice is read from the prescription as written. Voice notes on rounds need no system at all.',
     'Admissions, billing and the bed board are usually on a system already. Those need only read access.',
     'If almost nothing is on a system, it is a different project, not a slower one. Better said now.'],
    'Tell me which of your records are still on paper.',
    ['What we bring', 'Read access', 'Almost nothing on a system'],
    ['What happens after the 6 PM freeze?', 'Which automation do we switch on first?', 'What does Tojo build itself?'],
    'Try the three settings, or flip the records yourself. The lamps show what still switches on.',
    'Automations · records on paper', 'Records on paper', 'Paper or system: what still works', 'Each record is on a system or on paper. Each lamp lights only when everything it needs is on a system.',
    {'type': 'sources', 'hint': 'Try a setting or flip a record. Pick a record to see what paper changes.', 'src_label': 'Your records', 'auto_label': 'What can switch on',
     'main': {'id': 'dis', 'tag': 'Main switch', 'name': 'Discharge, automated', 'short': 'discharge', 'line': 'Built first, so its times are real'},
     'sources': [{'id': 'opd', 'name': 'OPD prescriptions', 'short': 'OPD advice', 'holds': 'Read from the page as written, paper or not', 'link': 'ours', 'point': 1},
                 {'id': 'voice', 'name': 'Voice notes on rounds', 'short': 'round notes', 'holds': 'The doctor speaks. Our recorder writes the note', 'link': 'ours', 'point': 1},
                 {'id': 'adt', 'name': 'Admissions and discharges', 'short': 'admissions', 'holds': 'Who came in, who left, which bed, and when', 'link': 'needed', 'point': 2},
                 {'id': 'bed', 'name': 'Bed board', 'short': 'bed board', 'holds': 'Which beds are empty, being cleaned or ready', 'link': 'needed', 'point': 2},
                 {'id': 'bill', 'name': 'Billing', 'short': 'billing', 'holds': 'When each bill closes and the next opens', 'link': 'needed', 'point': 2},
                 {'id': 'ip', 'name': 'Inpatient notes', 'short': 'inpatient notes', 'holds': 'The stay so far, for each patient', 'link': 'needed'}],
     'automations': [{'name': 'Admission steps timed', 'needs': ['adt']},
                     {'name': 'Dead bed time, measured', 'needs': ['bill', 'adt']},
                     {'name': 'Tomorrow’s bed map', 'needs': ['dis', 'adt', 'opd', 'ip']},
                     {'name': 'Who frees a bed, predicted', 'needs': ['ip', 'voice']},
                     {'name': 'Call-in times, bed by bed', 'needs': ['dis', 'adt', 'bed', 'opd']},
                     {'name': 'Emergency beds held back', 'needs': ['adt'], 'point': 3}],
     'default_on': ['opd', 'voice', 'adt', 'bed', 'bill'],
     'presets': [{'label': 'Mostly on a system', 'on': ['opd', 'voice', 'adt', 'bed', 'bill', 'ip', 'dis']},
                 {'label': 'Notes on paper', 'on': ['opd', 'voice', 'adt', 'bed', 'bill', 'dis']},
                 {'label': 'Almost all on paper', 'on': ['opd', 'voice']}],
     'condition': 'Paper notes do not stop the build. They make the part we bring bigger, and the timeline longer.',
     'sheets': [S('opd', 'We bring this', 'OPD prescriptions', 'The advice to admit is read from the prescription as written. Paper or screen makes no difference to this part.',
                  [('If on paper', 'Still works', 'start')], 'Are your OPD prescriptions written by hand?'),
                S('voice', 'We bring this', 'Voice notes on rounds', 'The doctor speaks on the round they already do. Our recorder turns it into a note. No system is needed on the ward.',
                  [('If on paper', 'Still works', 'start')], 'Do your doctors write round notes by hand today?',
                  hand=('the treating doctor', 'Speaks the note on the round.')),
                S('adt', 'Has to be there', 'Admissions and discharges', 'Almost every lamp needs this record. If it is kept in a register, we would have to build the record first.',
                  [('If on paper', 'Most lamps stay dark', 'target')], 'Is admission and discharge kept on a system or a register?'),
                S('bed', 'Has to be there', 'Bed board', 'Call-in times need to see which beds are ready. A whiteboard cannot be read by the engine.',
                  [('If on paper', 'No call-in times', 'target')], 'Is your bed board a system, a sheet or a whiteboard?'),
                S('bill', 'Has to be there', 'Billing', 'Billing is almost always on a system. The report joins bill close and bill open against the same bed.',
                  [('If on paper', 'Dead bed time cannot be measured', 'target')], 'Is your billing on a system?'),
                S('ip', 'Has to be there', 'Inpatient notes', 'If these are on paper, voice notes on rounds can fill much of the gap. That is more for us to build.',
                  [('If on paper', 'We build more of it'), ('Prediction', 'Coarser at first')], 'Which parts of the inpatient file are on paper?')]},
    {'label': 'Almost nothing on a system', 'value': 'A different project', 'state': 'start', 'sub': 'Not a slower one. The part we bring gets much bigger, and the timeline changes with it.'},
    ('Next: what happens after the 6 PM freeze', 'What happens after the 6 PM freeze?'), ('Tell me what is on paper', 'These records are still on paper with us: ')))

# ---------------------------------------------------------------------------------------------- 06 · after the freeze (nightshift)
T.append(turn(6, 'What happens after the 6 PM freeze?',
    'From bed-management.md §7.4.1: the 6 PM freeze, (d) beds held for emergencies, (e) call-in timing, Admission TAT under 30 minutes and admitted by about noon; Nagpur arrival and in-bed times.',
    ['After the freeze the engine keeps watch overnight. By morning everyone knows which bed frees when.'],
    ['At 6 PM the plan freezes. Each patient coming in gets one bed and a call-in time.',
     'Emergencies at night use the beds held back. The planned beds stay as they are.',
     'In the morning, real discharge times come in. Patients arrive and finish paperwork before the bed frees.'],
    'Tell me what a usual night looks like for emergencies.',
    ['The freeze', 'Beds held back', 'Paperwork done early'],
    ['Which automation do we switch on first?', 'How many beds are held for emergencies?', 'How does the day change on the wards?'],
    'Play the night, or move the clock. Pick a station to open it.',
    'Automations · after the freeze', 'The night shift', 'From the freeze to a bed by noon', 'What runs between 6 PM and noon the next day, and what is ready by morning.',
    {'type': 'nightshift', 'hint': 'Play the night or move the clock. Pick a station to open it.', 'from': '18:00', 'to': '17:00', 'start_at': '18:00', 'play': 'Play the night', 'ready_label': 'Ready by',
     'clock': ['18:00', '02:00', '08:00', '10:00', '12:00', '14:00'],
     'night': {'from': '21:00', 'to': '07:00', 'label': 'The night'},
     'goal': {'at': '12:00', 'label': 'In bed by', 'source': 'target'},
     'stations': [{'at': '18:00', 'title': 'The plan is frozen', 'makes': 'One bed per planned admission', 'point': 1},
                  {'at': '18:30', 'title': 'Call-in times go out', 'makes': 'A time for each patient coming in', 'hand': True},
                  {'at': '02:00', 'title': 'An emergency comes in', 'makes': 'A held bed is used, planned beds untouched', 'point': 2},
                  {'at': '08:00', 'title': 'Morning discharges confirmed', 'makes': 'Real times, logged as they happen', 'hand': True},
                  {'at': '10:00', 'title': 'Bills close, beds are cleaned', 'makes': 'Each bed’s free time, checked'},
                  {'at': '11:00', 'title': 'Patients arrive and do paperwork', 'makes': 'Paperwork done before the bed frees', 'hand': True, 'point': 3}],
     'condition': 'Today your patient arrives at 1 PM and is in bed at 4:30 PM. The goal is in bed by noon.',
     'sheets': [S('freeze', '6 PM', 'The plan is frozen', 'Tomorrow’s plan is fixed. Every planned patient has one bed. What is still without a bed is shared with everyone.',
                  [('Makes', 'One bed per planned admission', 'start'), ('Also makes', 'The list still without a bed')], 'How many planned admissions do you take on a usual day?'),
                S('call', '6:30 PM', 'Call-in times go out', 'Each patient is told when to come. The time is worked back from when their bed will be free.',
                  [('Makes', 'One call-in time per patient')], 'How do you reach planned patients today?',
                  hand=('the admissions desk', 'Calls or messages each patient their time.')),
                S('er', '2 AM', 'An emergency comes in', 'A number of beds is held back for emergencies, from two to three years of your own trend. The emergency takes one of those.',
                  [('Uses', 'A bed held back'), ('Planned beds', 'Untouched')], 'How many emergencies come in on a usual night?'),
                S('dis', '8 AM', 'Morning discharges confirmed', 'Each discharge is confirmed on the morning round and logged as it happens. The engine checks the times against the plan.',
                  [('Reads', 'Real discharge times')], 'When do your first discharges usually happen?',
                  hand=('the treating doctor', 'Confirms each discharge on the morning round.')),
                S('clean', '10 AM', 'Bills close, beds are cleaned', 'As bills close and beds are cleaned, each bed’s free time is checked against the call-in times.',
                  [('Checks', 'Free time against call-in time')], 'Who tells the desk a bed is cleaned?'),
                S('arrive', '11 AM', 'Patients arrive and do paperwork', 'The patient comes before the bed is free. Paperwork is done while the bed is cleaned. In bed by noon, not 4:30 PM.',
                  [('Today', 'In bed at 4:30 PM', 'start'), ('Goal', 'In bed by noon', 'target')], 'Where do patients wait while paperwork is done?',
                  hand=('the admissions desk', 'Finishes the paperwork while the bed is cleaned.'))]},
    {'label': 'Admission time, the goal', 'value': 'About 30 minutes', 'state': 'target', 'sub': 'Today about 3½ hours, 1 hour of it paperwork. With call-in times, paperwork is the only step left.'},
    ('Next: which automation switches on first', 'Which automation do we switch on first?'), ('Tell me about your nights', 'On a usual night with us: ')))

# ---------------------------------------------------------------------------------------------- 07 · what switches on first (panel) · last Automations turn
T.append(turn(7, 'Which automation do we switch on first?',
    'From transcript 31 (the first step: read access, then four weeks of measuring) and bed-management.md §7.4.1 and §7.4.2. The last Automations turn: the day on the wards, the people, the team and the measures are only named here.',
    ['Two automations switch on first. They need only read access and one billing report.'],
    ['Admission steps timed. Each of the five steps is stamped, so paperwork shows apart from waiting.',
     'Dead bed time measured. Bill close against bill open, bed by bed. Your own number, before anything changes.',
     'Then discharge is built, and the bed map on top. That step also changes how the day runs on the wards.'],
    'When you are ready, we can look at how the day changes on the wards.',
    ['Admission steps timed', 'Dead bed time measured', 'Discharge built', 'The bed map'],
    ['How does the day change on the wards?', 'Who needs to agree to this?', 'How would we know it is working?'],
    'Step through the build. Pick a row to see when it switches on.',
    'Automations · what comes first', 'The build panel', 'Two lamps first, then the rest', 'Each row is one automation. Step through the build and watch which lights first.',
    {'type': 'panel', 'hint': 'Step through the build. Pick a row to see when it switches on.', 'phases_label': 'The four steps', 'rows_label': 'Automation', 'foot': 'Nurses’ station · build panel',
     'phases': [{'when': 'About two weeks', 'name': 'Read access'}, {'when': 'Four weeks', 'name': 'Measure what happens now'},
                {'when': 'Step 3', 'name': 'Discharge built'}, {'when': 'Step 4', 'name': 'The bed map on top'}],
     'mains': [{'tag': 'Main switch 1', 'name': 'Read access from IT', 'line': 'The systems you already run', 'on_at': 0},
               {'tag': 'Main switch 2', 'name': 'Discharge, automated', 'line': 'The bed plan runs on its times', 'on_at': 2}],
     'automations': [{'name': 'Admission steps timed', 'line': 'Switched on first', 'stages': [1, 3, 3, 3], 'point': 1},
                     {'name': 'Dead bed time, measured', 'line': 'Switched on first', 'stages': [1, 3, 3, 3], 'point': 2},
                     {'name': 'Discharge times checked', 'line': 'Comes with discharge', 'stages': [0, 0, 3, 3], 'point': 3},
                     {'name': 'Who frees a bed, predicted', 'line': 'Learns from the four weeks', 'stages': [0, 1, 2, 3]},
                     {'name': 'Tomorrow’s bed map', 'line': 'Built on discharge', 'stages': [0, 0, 1, 3], 'point': 4},
                     {'name': 'Call-in times, bed by bed', 'line': 'The last to switch on', 'stages': [0, 0, 1, 3]}],
     'sheets': [S('steps', 'On in step 2', 'Admission steps timed', 'Each of the five admission steps is stamped. You see your real 3½ hours, step by step, before anything changes.',
                  [('Needs', 'Read access only'), ('Makes', 'Your own admission times', 'start')], 'Which admission step feels slowest to you?'),
                S('dbt', 'On in step 2', 'Dead bed time, measured', 'One report joins bill close and bill open against the same bed. Your 4 to 5 hours becomes a number you track weekly.',
                  [('Needs', 'One billing report'), ('Makes', 'Dead bed time, bed by bed', 'start')], 'Has anyone measured this before?'),
                S('dis', 'On in step 3', 'Discharge times checked', 'Comes with discharge itself. From here on, the bed side plans on real times.',
                  [('Needs', 'Discharge, automated', 'target')], 'Who records discharge times today?'),
                S('pred', 'Learns from step 2', 'Who frees a bed, predicted', 'The four weeks of measuring give it your own stays. It is tested before the bed map uses it.',
                  [('Needs', 'Inpatient notes, past stays')], 'How many procedures make up most of your admissions?'),
                S('map', 'On in step 4', 'Tomorrow’s bed map', 'Built on top of discharge. A first pass at 2 PM and a freeze at 6 PM, every day.',
                  [('Needs', 'Discharge, predictions, OPD advice')], 'How many planned admissions on a usual day?',
                  hand=('the Bed Manager', 'Checks the 6 PM freeze before it goes out.')),
                S('call', 'On in step 4', 'Call-in times, bed by bed', 'The last lamp. It needs everything above, because it tells real patients when to come.',
                  [('Needs', 'The bed map and discharge times'), ('Makes', 'One call-in time per bed', 'target')], 'Who should check call-in times at first?')]},
    {'label': 'Switched on first', 'value': 'Two automations', 'state': 'outcome', 'sub': 'Both run on read access and one report. Each gives your own number before anything else changes.'},
    ('Next: how the day changes on the wards', 'How does the day change on the wards?'), ('Tell me what to measure first', 'We would like to measure this first: ')))

for s in T:
    s['review'] = {'status': 'approved', 'date': '2026-10-06', 'note': 'Approved 6 Oct with the Bed Management Automations turns.'}
    json.dump(s, open(os.path.join(HERE, s['turn']['id'] + '.json'), 'w', encoding='utf-8'), ensure_ascii=False, indent=1)

NOTES = {'bm-au-01-B.json': 'Approved 1 Oct 2026: Sample B is the turn (the engine through one day). A and C are kept as templates.',
         'bm-au-02.json': 'Prompt 1 of bm-au-01. The library helper: the five asks of your IT team.',
         'bm-au-03.json': 'The library relay: the hand-over from discharge to the bed, today and linked.',
         'bm-au-04.json': 'The library thinker: how the engine predicts which beds free up. The doctor decides.',
         'bm-au-05.json': 'The library switchboard with three settings for paper. The night background starts here.',
         'bm-au-06.json': 'The library night shift: from the 6 PM freeze to a bed by noon.',
         'bm-au-07.json': 'The station panel: what switches on first. The last Automations turn. Wards, people, team and measures are only named.'}
json.dump({'place': 'Automations', 'turns': [{'file': f, 'note': n} for f, n in NOTES.items()]}, open(os.path.join(HERE, 'turns.json'), 'w', encoding='utf-8'), ensure_ascii=False, indent=1)
print('wrote bm-au-02 to bm-au-07 and turns.json')
